

         ***********************************Create your own Resume using JSON Foramt*********************************************

let myResume={
    "basics": {
      "name": "SURAJ PARKASH",
      "email": "surajchoudhary604@gmail.com",
      "phone": 6395170331,
      "degree": "B.tech",
      "location": {
        "address": "U block dlf phase-3 gurgaon",
        "postalCode": 122001,
        "city": "gurgaon",
        "state": "haryana",
        "country": "India"
      },
      
    },
    "work": [
      {
        "company": "WNS",
        "position": "Associate",
        "startDate": "2022-08-04",
        "endDate": "Currentlly Working",
      },
    ],
    "education": [
      {
        "institution": "UIET kurukshetra University Kurukshetra haryana",
        "department": "Computer science engg",
        "studyType": "fulltime",
        "batch start year": 2012,
        "batch end year": 2016,
        "gpa": 7.5,
      }
    ],
    "skills": [
      {
        "name": "javascript",
        "level": "beginer",
        "project": [
          "Task builder"
        ]
      }
    ],
    "languages": [
      {
        "language": "Hindi,English",
      }
    ],
    "interests": [
      {
        "name": "Dancing,Singing,",
      }
    ]
  }
  console.log(myResume);